modLoader = "javafml"
loaderVersion = "[1,)"
license = "${license}"
issueTrackerURL= "${issues_url}"
[[mods]]
    modId = "${mod_id}"
    version = "${version}"
    displayName = "${mod_name}"
    displayURL = "${sources_url}"
    logoFile="${mod_id}_icon.png"
    authors = "${mod_author}"
    description = '''${description}'''
[[mixins]]
    config = "${mod_id}.mixins.json"
[[dependencies.${mod_id}]]
    modId = "neoforge"
    type="required"
    versionRange = "${neoforge_version_range}"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.${mod_id}]]
    modId = "minecraft"
    type="required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"
